# Site settings

name: Pearce Ropion
title: Pearce Ropion | Designer & Developer
email: pearce.ropion@me.com
description: >-
  Creative front end developer with a mind for compelling designs that spring to life to create web applications that are stunning, both visually and functionally.
baseurl: ""
url: "https://pearce-ropion.com"
email: pearce.ropion@me.com
social:
  - title: email
    url: mailto:pearce.ropion@me.com
  - title: Twitter
    url: mailto:pearce.ropion@me.com
  - title: Facebook
    url: https://www.facebook.com/pearce.ropion.9
  - title: Github
    url: https://www.github.com/pearce-ropion
  - title: Linkedin
    url: https://www.linkedin.com/in/pearce-ropion/

github_username:  pearce-ropion

# Build settings
markdown: kramdown
plugins:
  - jekyll-minifier
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files:
  - CNAME
  - .git
  - .gitignore
